### ISSUE TITLE
Number at right side of green lines

### ISSUE THREAD

**Issue by cczona** [colszowka/simplecov#184]
What is the meaning of the number at the right side of green lines in coverage detail?

i.e.

1   def foo()   1   <---
2     baz         23 <---
3  end

**Comment by Steinitch** [comment]
Is there anyway to know what tests 'hit' the line?

**Comment by bf4** [comment]
@Steinitch Not at this time.  Until recently, the Coverage module in the ruby standard library did not let you start and stop it, which made it difficult to get a before and after for individual tests.    Per http://tenderlovemaking.com/2015/02/13/predicting-test-failues.html looks like we may be able to do this with more work on future versions of Ruby. A PR or issue relating to that is welcome.

Otherwise, please see https://github.com/colszowka/simplecov/issues/340 for some more information
