### ISSUE TITLE
JRuby includes coverage for .simplecov

### ISSUE THREAD

**Issue by donv** [colszowka/simplecov#478]
Opening this for guidance and discussion.  If you have a chat channel, I'd prefer that :)

I am trying to solve the last JRuby failure:

https://travis-ci.org/colszowka/simplecov/jobs/118230188#L234

JRuby includes `.simplecov` in the list of covered files.  Is that wrong?  It only happens for `Scenario: Using configure block after start`, and code (`SimpleCov.configure`) in `.simplecov` is run after the `SimpleCov.start`call has completed.

Seems like including `.simplecov` in the list of covered files could be considered correct behavior.

I can try setting up the test to have different expectations for JRuby and others.  What do you think?

**Comment by colszowka** [comment]
Hmm, that is interesting. Technically, I guess since it is a ruby source file that is being loaded, one might want to have coverage applied, but on the other hand I think we should try to keep things similar between ruby implementations, and MRI Coverage does not seem to pay attention to this file (most likely because we use [load](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L102) instead of require, and if I remember correctly MRI coverage only is supposed to track `require`d files).

I would suggest to add a jruby-specific filter for either `.simplecov` or (probably preferrably) `!EXTNAME == .rb` to https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb - maybe as a separate adapter like the `root_filter`, which then gets a conditional load in https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L46

**Comment by donv** [comment]
I checked the doc, and it explicitly states that loaded code should be covered:

http://ruby-doc.org/stdlib-2.3.0/libdoc/coverage/rdoc/Coverage.html

Submitted a PR #479 for conditional expectation for JRuby.

I am willing to go another way if you still want that.

**Comment by PragTob** [comment]
With #547 we probably don't need this anymore, more reasoning in #479 still lots of thanks :tada:
