### ISSUE TITLE
simplecov testing lib coverage instead of app

### ISSUE THREAD

**Issue by dsexton** [colszowka/simplecov#498]
When attempting to measure a rails app tested with cucumber and rspec, cucumber is measuring code coverage of cucumber instead of my rails app. Rspec coverage is working fine.

After running cucumber:

```
21 scenarios (21 passed)
119 steps (119 passed)
1m11.401s
Coverage report generated for Cucumber Features to /Users/dsexton/.rvm/gems/ruby-2.3.1/gems/cucumber-2.3.3/coverage. 2821 / 3796 LOC (74.32%) covered.
```

<img width="1383" alt="code_coverage_for_cucumber-2_3_3_" src="https://cloud.githubusercontent.com/assets/474304/15300367/42d04b50-1b76-11e6-8696-942880601327.png">
## Info

simplecov version 0.11.2

``` ruby
# .simplecov
SimpleCov.start :rails
```

``` ruby
# features/support/env.rb
require 'simplecov' if ENV['SIMPLECOV']
```

**Comment by PragTob** [comment]
Hi there,

this is because cucumber seems to reside in your own `lib/` folder. As it is also common/intended for code of your application to be there this folder is tracked and not ignored.

you can use `add_filter` to ignore folders, which you could do for `lib/cucumber` although I'd rather suggest you move `cucumber` and others to a separate `vendors` folder or something and ignore that as a whole :)
