### ISSUE TITLE
Can I exclude 'class' and 'def' files from the report?

### ISSUE THREAD

**Issue by sleekweasel** [colszowka/simplecov#509]
While I know that, technically, class and def lines are executable in Ruby, that information isn't useful: I only want the report to list code that's really code (as opposed to an implementation detail of Ruby).

Can I configure things so that 'class' and 'def', and @@field initialiser lines are excluded from 'covered' and 'total' lines?

Since I'm using cucumber, could I similarly arrange for 'Given', 'When', and 'Then' lines to be excluded too?

**Comment by colszowka** [comment]
@sleekweasel No, this is not possible for simplecov because it uses the [Coverage](http://ruby-doc.org/stdlib-2.3.1/libdoc/coverage/rdoc/Coverage.html) lib from Ruby STDLIB, and that does not offer this kind of behaviour. You could probably use a Ruby parser to analyze your source and filter those out manually, but I'd consider that very much out of scope for simplecov.

Regarding Cucumber, you should consider [filtering out](https://github.com/colszowka/simplecov#filters) your `features/support` directory

**Comment by sleekweasel** [comment]
Fair enough. I'll hack something up with regexps, since I can rely on the first word in the line.

It's not the entire given when then clause I want to filter, just the declaration line.
