### ISSUE TITLE
Status of JRuby Support

### ISSUE THREAD

**Issue by hube** [colszowka/simplecov#524]
What is the status of support for the various flavors of Ruby, in particular JRuby? Is JRuby 9000 supported? What about JRuby 1.7? The "Ruby version compatibility" section of the README has not been updated [since 2011](https://github.com/colszowka/simplecov/commit/1b13859b7fb44102de14e04658e12adae7eced21#diff-cb3e0f2c76a671c083e8f001970f4631).

**Comment by olleolleolle** [comment]
Hi!

Since 3 months, the Travis build includes JRuby HEAD: https://github.com/colszowka/simplecov/commit/21e2dd8bf13b064cb97bb309ce771bbef348dece

The [Travis build matrix](https://travis-ci.org/colszowka/simplecov) shows that the test suite passes on jruby-head, although it sits among the "Allowed failures".

**Comment by PragTob** [comment]
FWIW I used to always happily use simplecov with JRuby and it seemed to work fine. These days on one of build tasks (that executes MORE) it only recognizes 2 files and then covers 73/94 lines while the task executing less is at 2619 / 2791 :'(

**Comment by PragTob** [comment]
It was preemptive and I should have looked at myself before.. some code changes lead to code being required before simplecov which of course it the ultimate rookie mistake. Can confirm working on JRuby :+1:

**Comment by hube** [comment]
Thanks for the update!
