### ISSUE TITLE
Lines hit just by test 

### ISSUE THREAD

**Issue by paulofabiano** [colszowka/simplecov#576]
Hi, guys! 
Maybe it is not an issue, maybe it is me but I have a PORO class instantiated in my controller. This instance variable is used to call a method. This method is not covered by my Minitest::Spec and, even though, simplecov report consider this 1 line method covered with 1 hit. If I remove this method call from the controller, I got the red line on the HTML report.

Is there a way to consider the hit just by the tests ? Calling all methods in my controller and not creating the class spec I guess is not the correct way to consider my file 100% covered. 

Thanks,
Paulo

**Comment by PragTob** [comment]
Hi there,

well the line must be covered somewhere in your tests because otherwise it wouldn't show up green. With covered I mean, some time during your test execution that controller must be hit calling that method and therefore it is covered. SinpleCov and the underlying library really just track which lines of code have been executed at all - especially if you do End2End testing that will be a lot :)

If you just want to see what's covered from your unit tests - only run your unit tests and then look at the report :)

Hope that helps + cheers,
Tobi
