### ISSUE TITLE
track_files option counts every line as relevant

### ISSUE THREAD

**Issue by etki** [colszowka/simplecov#600]
Hi!

It seems that files that are attached using track_files option are not analyzed for contents and `relevant_lines` count for those files is equal to `lines` count. This shouldn't bring any harm by itself, but in my case i have three accumulating test runs that upload their results to Coveralls - and because of that, at the end of the third run Coveralls thinks that i have 500 relevant lines more than i actually have and gives me 60% (while it is around 95% in reality).
I think i'll manage to create a fix on my side (by running Coveralls tool by hand)< but it would be wonderful if SimpleCov would provide such feature out-of-the-box.

**Comment by PragTob** [comment]
Thanks for the report!

That'd be... weird to go unnoticed so long. I hope it's something else. Iirc things that are added through track_files should just affect the files simplecov takes into account at all.

If you could provide a script to reproduce, that'd be wonderful in figuring this out. Otherwise I'd have to wip something up and time isn't exactly on my side right now :)

Also patches are of course very welcome!

**Comment by etki** [comment]
@PragTob actually i think this is quite normal - the most probable options is that track_files only reads files, but doesn't require them, so it doesn't have information about relevant lines on hand. I'll try to reproduce this in a single repo when i can.

**Comment by odlp** [comment]
I think this will be fixed by https://github.com/colszowka/simplecov/pull/605

**Comment by PragTob** [comment]
Fixed by #605 :tada:
