### ISSUE TITLE
Ruby 2.4.1 segfault

### ISSUE THREAD

**Issue by RobinDaugherty** [colszowka/simplecov#615]
I'm getting sporadic crashes in Ruby. To reproduce:

- macOS 10.12.6 or Linux ([Travis Trusty environment](https://travis-ci.org/charliesome/better_errors/jobs/268416120) for example)
- Ruby 2.4.1
- SimpleCov 0.14.1 or 0.15.0 or the current master branch

Unfortunately the crashes have different backtraces each time.

The segfault only occurs if simplecov is `start`ed, it does not occur if the gem is only required.

The bracktraces range from rspec to simplecov itself.

[This Travis build's failed jobs](https://travis-ci.org/charliesome/better_errors/builds/268416105) has some examples that were using Coveralls, but I got the same results locally with only SimpleCov.

[Some examples of crash logs from my Mac using only SimpleCov](https://gist.github.com/RobinDaugherty/28276923a28be31f5c33e55d3701ba42).

**Comment by PragTob** [comment]
:wave: 

First thanks for the good bug report and the time and research you put into this.

Honestly, I don't know what to do though :man_shrugging: 

Have you reported this to ruby core? Feel free to CC me in. Simplecov isn't using any C-extensions or something of the like that'd cause a segfault. We use the standard library coverage tool (which of course is implemented in C though). My fear would be that it's something in ruby itself that changed ([coverage hasn't changed in a while](https://github.com/ruby/ruby/blob/202bbda2bf5f25343e286099140fb9282880ecba/ext/coverage/coverage.c)) and causes these errors now in that specific combination. 

You could try it by [just running the ruby standard library coverage](https://ruby-doc.org/stdlib-2.4.1/libdoc/coverage/rdoc/Coverage.html) to see if that's the culprit.

Otherwise, I guess we'd have to find a "good" simplecov version and bisect to find where we do something so hardcore it crashes ruby. 

Either way, both would be ruby bugs imo because no ruby code should crash the ruby interpreter :)

**Comment by RobinDaugherty** [comment]
I agree, this is basically an MRI issue anyway, regardless of how I reproduce it. I can also confirm that running it with just `Coverage` reproduces this issue, so it's definitely not a SimpleCov issue.

I'm working to boil it down to a reproducible test case, and I'll open something with the MRI team.

**Comment by RobinDaugherty** [comment]
This seems to be my issue, and it looks like a fix will be included in 2.4.2. https://bugs.ruby-lang.org/issues/13305

**Comment by PragTob** [comment]
Thanks a lot, looking forward to the fix. Although kind of scary that it lived in 2.4 for that long :scream:
