### ISSUE TITLE
Missing files from `lib/` for Sequel plugin

### ISSUE THREAD

**Issue by AlexWayfer** [colszowka/simplecov#749]
I have a Sequel plugin: https://github.com/AlexWayfer/sequel-enum_values/tree/fix_coverage_reports

And don't see a coverage for `lib/` files:

![image](https://user-images.githubusercontent.com/6510020/66702435-4b4b5a80-ed10-11e9-973d-18ef82877b25.png)

* `simplecov (0.17.1)`
* `rspec (3.9.0)`
* `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`

**Comment by PragTob** [comment]
Hi there,

it would have been nice if you tried the [troubleshooting](https://github.com/colszowka/simplecov#troubleshooting) section before you opened an issue.

Adding a couple of debugs as suggested there I see:

```
tobi@speedy:~/github/sequel-enum_values(fix_coverage_reports)$ be rspec
loaded # your lib file being loaded
spec helper start # spec_helper and hence SimpleCov being loaded
started
```

Which means, the file is loaded before SimpleCov ever starts so it can't know about it.

A bit of digging reveals that this is because you load your entire library in the gemspec:

```
require_relative 'lib/sequel/plugins/enum_values'

Gem::Specification.new do |s|
```

I'd suggest putting the version definition into a separate file or just inlining it and hence removing the require.

Cheers

**Comment by AlexWayfer** [comment]
> A bit of digging reveals that this is because you load your entire library in the gemspec:

Thank you very much for your help. This is definitely my bad. I didn't mind that I made such thing some time ago.
