### ISSUE TITLE
Kernel.exec in code causes missing coverage

### ISSUE THREAD

**Issue by MSP-Greg** [colszowka/simplecov#752]
Ok, I know this is an edge case, but maybe someone has some suggestions.

Trying to get valid coverage for Puma.  There are different ways to restart Puma, and one way involves `Kernel.exec` in the code.

There is code that runs only when this is done, some of the code is immediately before the  `Kernel.exec`, and some is immediately after.

The 'after' code is shown as covered, but the 'before' code is not.

Any suggestions?  TIA, Greg

**Comment by colszowka** [comment]
From a brief glance this sounds like a bug in the coverage stdlib itself, could you maybe try to reproduce the issue as isolated as possible using coverage itself? Then this could be filed as a bug in ruby itself and everyone benefits

**Comment by bf4** [comment]
are you testing coverage in puma/puma or you're running puma in your test suite?

If you're running code in prod, coverband may be better suited

**Comment by MSP-Greg** [comment]
@bf4 - Testing coverage in puma/puma.

@colszowka - You're probably right, although I haven't tried any code immediately before the `Kernel.exec' code...

**Comment by MSP-Greg** [comment]
**Off-topic:** Got frustrated, added SimpleCov master to a doc site I maintain, typically updated daily or better...:

https://msp-greg.github.io/simplecov/

Noticed that version.rb is outdated. I'd do a PR, but some want it showing 0.17.1, others 0.17.2.pre:
https://github.com/colszowka/simplecov/blob/6b8d395541767941e0b07b1aa5cecd9a6ab4ece9/lib/simplecov/version.rb#L1-L5

**Comment by PragTob** [comment]
@MSP-Greg regrding the version, true it hasn't been updated in master but that's because the release was done on an 0.17 branch, master has updates unrelated. I usually only update the version shortly before a release but we can also update it to 0.18.0-pre to avoid confusion like this in the future

**Comment by MSP-Greg** [comment]
Thanks.  I've debated whether to remove the version info from the main doc page...

**Comment by deivid-rodriguez** [comment]
@MSP-Greg Not sure if this will be useful to you, but I suffered from "no coverage inside nested processes" issues. The problem in my case was that that subprocesses were setting the same `SimpleCov.command_name` (usually the name of the test framework), so their coverage would overwrite the previous coverage. The trick is to give the subprocesses a unique command name, so that their coverage is properly merged with the previous coverage and not overwritten. In my case, I'm doing it by setting an environment variable with a unique name for each test before shelling out, and then setting that to `SimpleCov.command_name` inside the `.simplecov` file.

See https://github.com/deivid-rodriguez/byebug/blob/1ccbf0e3632db3879e5dd7633d0fc2a5c734a4c7/test/support/utils.rb#L259 and https://github.com/deivid-rodriguez/byebug/blob/4b8a289500a8ae1e3bdf30c7aceec50ce0cdb6b7/.simplecov#L3.

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Thanks.  I tried something similar, and the 'coverage' summary did seem to list all of the 'coverage data instances' being 'collected'.

It still seemed to not show coverage where I knew tests were covering the code.  I need to revisit it...

**Comment by PragTob** [comment]
@MSP-Greg any progress here or a smaller reproducible case that either we or ruby-core can take a look at?

**Comment by MSP-Greg** [comment]
@PragTob 

Sorry for the delay.  The error was happening with Puma testing, but I've been working with MinGW Ruby and other things.  I'll revisit, but it will be a while.

I'll close and when I get back to it, I'll report back...

**Comment by PragTob** [comment]
@MSP-Greg thank you!
