### ISSUE TITLE
SimpleCov Reporting Differences Between v0.17.1 and v0.18.0

### ISSUE THREAD

**Issue by vanessadean** [colszowka/simplecov#851]
Wanted to surface this issue that has already been reported to Code Climate: https://github.com/codeclimate/codeclimate/issues/937

We ran into same error using simplecov in conjunction with Code Climate after upgrading from 0.17.1 to 0.18.0:

```
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-test-reporter after-build
```

Here is the version of Code Climate we are running: 

```
RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-netcgo-linux-amd64 -o /usr/local/bin/cc-test-reporter && \
    chmod +x /usr/local/bin/cc-test-reporter
```

Thanks!

**Comment by PragTob** [comment]
Hi @vanessadean ,

thanks for the report :green_heart: 

This is a known issue and you can find more background on it here: https://github.com/codeclimate/test-reporter/issues/413

The short version from my side:

* code climate integrates with us through an implementation detail whose format was never meant for integration or was documented or anything like that
* we mentioned this [over 2 years ago](https://github.com/colszowka/simplecov/pull/637#issuecomment-340076405)
* Before releasing this we gave them notice where communication at one point fizzled out a bit https://github.com/codeclimate/test-reporter/issues/413 (also pointing out other problems with this)
* Now it's broken
* I'll still try to work with them to find a solution that is doable. I'm admittedly not ecstatic about having to change stuff in SimpleCov so that a third party service can work but of course I want people to be able to use SimpleCov and CodeClimate.

So we'll see where/how this goes.

I'll close this issue though, imo the main issue for this is: https://github.com/codeclimate/test-reporter/issues/413
