### ISSUE TITLE
Branch coverage for boolean operators

### ISSUE THREAD

**Issue by sedubois** [colszowka/simplecov#921]
Unlike with if/else or ternary operators, I did not find how to obtain branch coverage for boolean operators such as `&&` and `||`:

<img width="1409" alt="Screenshot 2020-08-21 at 11 52 32" src="https://user-images.githubusercontent.com/4217871/90877819-fa32db00-e3a4-11ea-864e-6df28cbea918.png">

However it works with if/else and the ternary operator (example here when calling with `number = 1`):

<img width="1409" alt="Screenshot 2020-08-21 at 11 47 56" src="https://user-images.githubusercontent.com/4217871/90877989-3c5c1c80-e3a5-11ea-822c-e058594757af.png">
<img width="1454" alt="Screenshot 2020-08-21 at 11 46 41" src="https://user-images.githubusercontent.com/4217871/90877980-38c89580-e3a5-11ea-900b-8cd963db5471.png">

Is branch coverage for boolean `&&` / `||` / `and` / `or` operators something that Ruby supports and is it feasible at all to have simplecov report this?

I have an app which uses Pundit for authorization policies whose methods often look like this:
```rb
  def resume?
    edit? && !auto_renews? && !plan_archived?
  end
```

Currently all these methods are marked completely "green" as long as they've been executed once. It would be awesome to have some more insight to know which tests are missing. Thanks for a very helpful library!

Running with:
- ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
- Rails 6.0.3.2 with the vanilla minitest framework
- simplecov 0.19.0
- `.simplecov` file contains `enable_coverage :branch`

**Comment by G-Rath** [comment]
@PragTob hope you don't mind me necro'ing this with a question (happy to create a new issue if you'd prefer): do you know if a request with ruby core was ever filed?

I've had next to no experience with bugs.ruby-lang.org so I wouldn't be surprised if I've not done the right search - the closest I've found is [the original request for branch coverage](https://bugs.ruby-lang.org/issues/13901) which you commented, and has this convo between [marcandre](https://bugs.ruby-lang.org/users/182) and [mame](https://bugs.ruby-lang.org/users/18):

> **marcandre**: 
> I imagine you are planning on covering ||, &&, &. and ? :, right?
>
> **mame**:
> ? : has been already supported. Yuichiro has experimentally implemented &. coverage. I think we should support || and && too.
> (Formerly, I had no intention of supporting them, but Yuichiro implemented column numbers, so now we will be able to do that.)

So it sounds like this isn't something anyone was against or (at the time) knew there was any particular unsolved technical challenge, it just maybe dropped off the radar?

~If that's the case and my searches have been correct in not finding an existing request, I think it'd be great to get that filed - if you would be ok doing that, I'd really appreciate it since I don't have an account and don't think I'll have much to contribute beyond a "+1", but I can register for an account otherwise and try to go through the filing process~

I've created https://bugs.ruby-lang.org/issues/22014
